[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "src/graphlow",
  "pyproject.toml",
  "README.md",
  "LICENSE",
]

[project]
name = "graphlow"
version = "0.0.2"
description = "graphlow provides graph processing features for physical simulation data (e.g., mesh)."
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "RICOS Co. Ltd." }]
requires-python = ">=3.10"
classifiers = ["Programming Language :: Python"]
dependencies = [
    "vtk==9.3.1",
    "pyvista>=0.43",
    "scipy>=1.14.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]

[dependency-groups]
dev = [
    { include-group = "test" },
    { include-group = "visualize" },
    { include-group = "lint" },
    { include-group = "docs" },
]
ci = [
    { include-group = "test" },
    { include-group = "lint" },
    { include-group = "docs" },
]
benchmark = [{ include-group = "test" }, { include-group = "visualize" }]
test = [
    "pytest>=8.0.2",
    "pytest-cov>=4.1.0",
    "pytest-benchmark>=5.1.0",
    "pytest-memray>=1.7.0",
    "pyinstrument",
]
lint = ["ruff>=0.9.6", "mypy>=1.8.0"]
visualize = ["polars", "plotly", "kaleido", "pydantic"]
docs = [
    "sphinx",
    "numpydoc",
    "pydata-sphinx-theme",
    "sphinxcontrib-mermaid",
    "sphinx-fontawesome",
    "sphinx-gallery",
    "sphinx-design",
    "sphinx-copybutton",
    "trame>=3.8.0",
    "trame-vtk>=2.8.15",
    "trame-vuetify>=2.8.1",
    "ipykernel>=6.29.5",
    "imageio"
]

[tool.uv]
default-groups = ["ci"]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "with_benchmark: Run test with the --benchmark-autosave option",
    "with_profile: Run test with memray / pyinstrument",
    "with_device: Run test with the --gpu option to use GPU",
]
addopts = [
    "--import-mode=importlib",
    "-m",
    "not with_benchmark and not with_profile and not with_device",
]

[tool.coverage.report]
ignore_errors = false
show_missing = true
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
